"""add download_speed and download_eta to videos

Revision ID: c8abb19185e5
Revises: 26c003361d5e
Create Date: 2026-02-17 09:56:38.064337
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c8abb19185e5'
down_revision: Union[str, None] = '26c003361d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('download_speed', sa.Float(), nullable=True))
    op.add_column('videos', sa.Column('download_eta', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'download_eta')
    op.drop_column('videos', 'download_speed')
    # ### end Alembic commands ###
